### ISSUE TITLE
Keep the Splash Screen open

### ISSUE THREAD

**Issue by leovarmak** [buz-zard/random#1]
How do can we keep the splash screen open for a period of time ? for example 6 seconds regardless of the page load

**Comment by karolis-sh** [comment]
Well, you could add timeout in `https://github.com/buz-zard/random/blob/master/electron-compile-1/src/main.js` 25th row.

Something like this:

```mainWindow.webContents.on('did-finish-load', () => {
  setTimeout(() => {
    mainWindow.show();

    if (loadingScreen) {
      let loadingScreenBounds = loadingScreen.getBounds();
      mainWindow.setBounds(loadingScreenBounds);
      loadingScreen.close();
    }
  }, 6000);
});
```

Note: I haven't tested this.
